// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// poisson_mixture_em_cpp
List poisson_mixture_em_cpp(NumericVector x, NumericVector s, double lambda1, double lambda2, double pi, int max_iter, double tol);
RcppExport SEXP _DenoIST_poisson_mixture_em_cpp(SEXP xSEXP, SEXP sSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP piSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_mixture_em_cpp(x, s, lambda1, lambda2, pi, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// poisson_mixture_batch_em_cpp
List poisson_mixture_batch_em_cpp(NumericVector x, NumericVector s, IntegerVector non_zero_indices, int batch_size, int n_epochs, double tau, double alpha, double lambda1, double lambda2, double pi);
RcppExport SEXP _DenoIST_poisson_mixture_batch_em_cpp(SEXP xSEXP, SEXP sSEXP, SEXP non_zero_indicesSEXP, SEXP batch_sizeSEXP, SEXP n_epochsSEXP, SEXP tauSEXP, SEXP alphaSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type non_zero_indices(non_zero_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_mixture_batch_em_cpp(x, s, non_zero_indices, batch_size, n_epochs, tau, alpha, lambda1, lambda2, pi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DenoIST_poisson_mixture_em_cpp", (DL_FUNC) &_DenoIST_poisson_mixture_em_cpp, 7},
    {"_DenoIST_poisson_mixture_batch_em_cpp", (DL_FUNC) &_DenoIST_poisson_mixture_batch_em_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_DenoIST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
