# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poisson_mixture_em_cpp <- function(x, s, lambda1, lambda2, pi, max_iter, tol) {
    .Call(`_DenoIST_poisson_mixture_em_cpp`, x, s, lambda1, lambda2, pi, max_iter, tol)
}

poisson_mixture_batch_em_cpp <- function(x, s, non_zero_indices, batch_size, n_epochs, tau, alpha, lambda1, lambda2, pi) {
    .Call(`_DenoIST_poisson_mixture_batch_em_cpp`, x, s, non_zero_indices, batch_size, n_epochs, tau, alpha, lambda1, lambda2, pi)
}

